---
version: '2.4'
services:
  ib-gateway:
    image: omdv/ib-gateway-docker:v1.3.3
    environment:
      - IB_ACCOUNT=${IB_USER_ID}
      - IB_PASSWORD=${IB_PASSWORD}
      - TRADE_MODE=${IB_TRADING_MODE}
    restart: always
    ports:
      - 4041:4041
      - 4042:4042

  ib-app:
    image: omdv/ib-app:${IB_APP_VERSION}
    environment:
      - IB_GATEWAY_HOST=ib-gateway
      - IB_GATEWAY_PORT=4041
      - STORAGE_BACKEND=file
    restart: on-failure
    volumes:
      - ./downloads:/data
    depends_on:
      - ib-gateway
