---
version: '3.4'
services:

  ib-gateway:
    image: ghcr.io/extrange/ibkr:10.19
    ports:
      - "127.0.0.1:6080:6080" # noVNC browser access
      - "127.0.0.1:8888:8888" # API access
    ulimits:
      nofile: 10000
    environment:
      USERNAME: ${IB_USER_ID}
      PASSWORD: ${IB_PASSWORD}
      TWOFA_TIMEOUT_ACTION: restart
      GATEWAY_OR_TWS: gateway
      IBC_TradingMode: ${IB_TRADING_MODE}
    restart: always
    healthcheck:
      test: pidof java || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  ib-api:
    build: ./api
    environment:
      - IB_GATEWAY_HOST=ib-gateway
      - IB_GATEWAY_PORT=8888
    ports:
      - "127.0.0.1:8000:80"
    # volumes:
    #   - ./api:/code/app
    restart: always
    healthcheck:
      test: pidof python || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    depends_on:
      ib-gateway:
        condition: service_healthy

  ib-bots:
    build: ./bots
    environment:
      - IB_GATEWAY_HOST=ib-gateway
      - IB_GATEWAY_PORT=8888
    volumes:
      # - ./bots:/code/app
      - ./downloads:/data
    restart: on-failure
    healthcheck:
      test: pidof python || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    depends_on:
      ib-gateway:
        condition: service_healthy

# debug
# docker run --name ibkr \
# -d -p "127.0.0.1:6080:6080" \
# -p "127.0.0.1:8888:8888" \
# --ulimit nofile=10000 \
# -e GATEWAY_OR_TWS=gateway \
# -e IBC_ReadOnlyApi=no \
# -e USERNAME=(gopass show homelab/ibkr/tws_user_id) \
# -e PASSWORD=(gopass show homelab/ibkr/tws_user_pass) \
# ghcr.io/extrange/ibkr:10.19
