---
version: '2.4'
services:
  ib-gateway:
    image: docker.io/omdv/ib-gateway:${IB_GATEWAY_VERSION}
    environment:
      - TWSUSERID=${IB_USER_ID}
      - TWSPASSWORD=${IB_PASSWORD}
      - TRADING_MODE=${IB_TRADING_MODE}
    restart: always
    ports:
      - 4041:4041
      - 4042:4042

  ib-app:
    image: docker.io/omdv/ib-app:${IB_APP_VERSION}
    environment:
      - IB_GATEWAY_HOST=ib-gateway
      - IB_GATEWAY_PORT=4041
      - STORAGE_BACKEND=file
    restart: on-failure
    volumes:
      - ./downloads:/data
    depends_on:
      ib-gateway:
        condition: service_healthy
