---
version: '3.4'
services:

  ib-gateway:
    image: ghcr.io/extrange/ibkr:10.19
    ports:
      - "127.0.0.1:6080:6080" # noVNC browser access
      - "127.0.0.1:8888:8888" # API access
    ulimits:
      nofile: 10000
    environment:
      USERNAME: ${IB_USER_ID}
      PASSWORD: ${IB_PASSWORD}
      TWOFA_TIMEOUT_ACTION: restart
      GATEWAY_OR_TWS: gateway
      IBC_TradingMode: ${IB_TRADING_MODE}
    healthcheck:
      test: pidof java || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s

  ib-app:
    build: ./app
    environment:
      - IB_GATEWAY_HOST=ib-gateway
      - IB_GATEWAY_PORT=8888
    volumes:
      - ./downloads:/data
    depends_on:
      ib-gateway:
        condition: service_healthy
