version: '3'

env:
  AWS_REGION: us-east-1
  AWS_AVAILABILITY_ZONE: us-east-1a
  GATEWAY_IMAGE: ghcr.io/extrange/ibkr:10.30
  APP_IMAGE: ghcr.io/omdv/ib-bots:latest

tasks:
  evd-up:
    cmds:
      - docker-compose -f docker-compose-evd.yaml up -d
    env:
      IB_GATEWAY_HOST: localhost
      IB_GATEWAY_PORT: 8888
    silent: true

  evd-down:
    cmds:
      - docker-compose -f docker-compose-evd.yaml down
    silent: true

  test:
    cmds:
      - docker-compose -f docker-compose-p4d.yaml up -d
    silent: true

  build-app:
    cmds:
      - cd app && poetry export -f requirements.txt --without-hashes --only main > requirements.txt
      - docker build -t omdv/ib-trading-app:latest ./app

  deploy:
    cmds:
      - pulumi up --yes

  default:
    - task: publish-images
    - task: deploy
