---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ibkr.fullname" . }}-gateway
  labels:
    {{- include "ibkr.labels" . | nindent 4 }}
    app.kubernetes.io/component: "gateway"
spec:
  replicas: {{ .Values.gateway.replicaCount }}
  selector:
    matchLabels:
      {{- include "ibkr.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "gateway"
  template:
    metadata:
      {{- with .Values.gateway.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ibkr.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: "gateway"
    spec:
      {{- with .Values.gateway.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ibkr.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.gateway.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.gateway.securityContext | nindent 12 }}
          image: "{{ .Values.gateway.image.repository }}:{{ .Values.gateway.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.gateway.image.pullPolicy }}
          ports:
            - name: api
              containerPort: {{ .Values.gateway.ports.api }}
              protocol: TCP
            - name: vnc
              containerPort: {{ .Values.gateway.ports.vnc }}
              protocol: TCP
          # livenessProbe:
          #   tcpSocket:
          #     port: api
          #   initialDelaySeconds: 120
          #   periodSeconds: 60
          # readinessProbe:
          #   tcpSocket:
          #     port: api
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          envFrom:
            - secretRef:
                name: {{ .Values.gateway.existingSecret }}
          env:
            - name: GATEWAY_OR_TWS
              value: {{ .Values.gateway.parameters.GATEWAY_OR_TWS | quote }}
            - name: TWOFA_TIMEOUT_ACTION
              value: {{ .Values.gateway.parameters.TWOFA_TIMEOUT_ACTION | quote }}
            - name: IBC_TradingMode
              value: {{ .Values.gateway.parameters.IBC_TradingMode | quote }}
            - name: IBC_ReadOnlyApi
              value: {{ .Values.gateway.parameters.IBC_ReadOnlyApi | quote }}
            - name: IBC_ReloginAfterSecondFactorAuthenticationTimeout
              value: {{ .Values.gateway.parameters.IBC_ReloginAfterSecondFactorAuthenticationTimeout | quote }}
          resources:
            {{- toYaml .Values.gateway.resources | nindent 12 }}
      {{- with .Values.gateway.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.gateway.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.gateway.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
