---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ibkr.fullname" . }}-gateway
  labels:
    {{- include "ibkr.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.gateway.ports.api }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "ibkr.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: "gateway"
