---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ibkr-data
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: "/pool/ibkr"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ibkr-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
  volumeName: pv-ibkr-data
