---
nameOverride: ""
fullnameOverride: "ibkr-bot"

serviceAccount:
  create: true
  annotations: {}
  name: ""

gateway:
  replicaCount: 1
  image:
    repository: ghcr.io/extrange/ibkr
    pullPolicy: IfNotPresent
    tag: "10.32.1l"

  # The name of the secret containing the credentials for the gateway
  # expecting USERNAME and PASSWORD variables
  existingSecret: "ibkr-gateway-secret"

  parameters:
    TWOFA_TIMEOUT_ACTION: "restart"
    GATEWAY_OR_TWS: "gateway"
    IBC_TradingMode: "live"
    IBC_ReadOnlyApi: "no"
    IBC_ReloginAfterSecondFactorAuthenticationTimeout: "yes"
  ports:
    api: "8888"
    vnc: "6080"
  imagePullSecrets: []
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

application:
  replicaCount: 1
  image:
    repository: ghcr.io/omdv/ib-trading-app
    pullPolicy: Always
    tag: "latest"
  existingConfigMap: "ibkr-app-config"
  existingSecret: "ibkr-app-secret"

  # needs existing claim if enabled
  persistence:
    enabled: false
    existingClaim: ""
    mountPath: "/data"

  imagePullSecrets: []
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
